#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

require_pattern() {
  local file="$1" pattern="$2" label="$3"
  grep -Eq "$pattern" "$ROOT/$file" || fail "$label missing in $file"
}

require_pattern ".agents/skills/harnessable/SKILL.md" "harnessable Rubric" "Rubric loop"
require_pattern ".agents/skills/harnessable/SKILL.md" "per-criterion" "per-criterion verdict table"
require_pattern ".agents/skills/harnessable/SKILL.md" "executing type" "executing type guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Designer" "Designer skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Asset Package" "Asset Package skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Project Manager" "Project Manager skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Dreamer" "Dreamer skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Dream Report" "Dream Report skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "last_collapse.json" "last collapse skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Evolver" "Evolver skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Evolution Report" "Evolution Report skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "last_evolution.json" "last_evolution skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "WORLD_MODEL.md" "World Model skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "world_models" "world models skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Execution Manifest" "Execution Manifest skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "docs/mandates/per" "PER skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "packages/\\*/PACKAGE.md" "Package adapter skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "packages/\\*/skills" "Package skills skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "Token budget" "Token budget skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "cost_per_1k_tokens" "Token cost skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "OPERATOR" "OPERATOR skill guidance"
require_pattern ".agents/skills/harnessable/SKILL.md" "PLAYWRIGHT" "PLAYWRIGHT skill guidance"

require_pattern "codex/qa.prompt.md" "Layer 1.*Acceptance Criteria" "Rubric Layer 1"
require_pattern "codex/qa.prompt.md" "Layer 2.*Verification Checklists" "Rubric Layer 2"
require_pattern "codex/qa.prompt.md" "Layer 3.*Completion Gate" "Rubric Layer 3"
require_pattern "codex/qa.prompt.md" "Per-Criterion Verdict Table" "Per-Criterion Verdict Table"
require_pattern "codex/qa.prompt.md" "fresh-context classifier" "QA classifier role"
require_pattern "codex/qa.prompt.md" "classifier.md" "QA classifier pattern reference"
require_pattern "codex/qa.prompt.md" "error-modes.md" "QA error modes reference"
require_pattern "codex/qa.prompt.md" "stop authority" "QA stop authority guidance"
require_pattern "codex/qa.prompt.md" "OPERATOR" "QA OPERATOR source"
require_pattern "codex/qa.prompt.md" "PLAYWRIGHT" "QA PLAYWRIGHT source"
require_pattern "codex/qa.prompt.md" "Overall verdict derivation" "overall verdict derivation"
require_pattern "codex/qa.prompt.md" "NEEDS_REVISION Handoff" "NEEDS_REVISION handoff"

require_pattern "codex/examples/qa.prompt.md" "three-layer Rubric" "example Rubric"
require_pattern "codex/examples/qa.prompt.md" "Per-Criterion Verdict Table" "example per-criterion table"
require_pattern "codex/examples/qa.prompt.md" "fresh-context classifier" "example QA classifier role"
require_pattern "codex/examples/qa.prompt.md" "classifier.md" "example QA classifier pattern reference"
require_pattern "codex/examples/qa.prompt.md" "error-modes.md" "example QA error modes reference"
require_pattern "codex/examples/qa.prompt.md" "stop authority" "example QA stop authority guidance"
require_pattern "codex/examples/qa.prompt.md" "OPERATOR" "example QA OPERATOR source"
require_pattern "codex/examples/qa.prompt.md" "PLAYWRIGHT" "example QA PLAYWRIGHT source"
require_pattern "codex/examples/qa.prompt.md" "NEEDS_REVISION" "example NEEDS_REVISION handoff"

require_pattern "codex/engineer.prompt.md" "Verification Checklists.*Rubric Layer 2" "Engineer Rubric Layer 2"
require_pattern "codex/engineer.prompt.md" "Entry .* Discovery Pass" "Engineer Discovery Pass"
require_pattern "codex/engineer.prompt.md" "find world_models/" "Engineer world models scan"
require_pattern "codex/engineer.prompt.md" "packages/\\*/PACKAGE.md" "Engineer package adapter scan"
require_pattern "codex/engineer.prompt.md" "harnessable:" "Engineer package harnessable block"
require_pattern "codex/engineer.prompt.md" "Enhancement Request" "Engineer PER guidance"
require_pattern "codex/engineer.prompt.md" "Execution Manifest" "Engineer Execution Manifest guidance"
require_pattern "codex/engineer.prompt.md" "docs/mandates/per/PER" "Engineer PER path guidance"
require_pattern "codex/engineer.prompt.md" "executing type" "Engineer executing type guidance"
require_pattern "codex/engineer.prompt.md" "Designer" "Engineer Designer guidance"
require_pattern "codex/engineer.prompt.md" "DESIGN_AMBIGUITY" "Engineer design ambiguity guidance"
require_pattern "codex/engineer.prompt.md" "OPERATOR" "Engineer OPERATOR guidance"
require_pattern "codex/engineer.prompt.md" "PLAYWRIGHT" "Engineer PLAYWRIGHT guidance"
require_pattern "codex/examples/engineer.prompt.md" "Verification Checklists as Rubric Layer 2" "Engineer example Rubric Layer 2"
require_pattern "codex/examples/engineer.prompt.md" "find world_models/" "Engineer example world models scan"
require_pattern "codex/examples/engineer.prompt.md" "packages/\\*/PACKAGE.md" "Engineer example package adapter scan"
require_pattern "codex/examples/engineer.prompt.md" "package command" "Engineer example package command guidance"
require_pattern "codex/examples/engineer.prompt.md" "Protocol Enhancement Request" "Engineer example PER guidance"
require_pattern "codex/examples/engineer.prompt.md" "Execution Manifest" "Engineer example Execution Manifest guidance"
require_pattern "codex/examples/engineer.prompt.md" "Designer" "Engineer example Designer guidance"
require_pattern "codex/examples/engineer.prompt.md" "DESIGN_AMBIGUITY" "Engineer example design ambiguity guidance"
require_pattern "codex/examples/engineer.prompt.md" "OPERATOR" "Engineer example OPERATOR guidance"
require_pattern "codex/examples/engineer.prompt.md" "PLAYWRIGHT" "Engineer example PLAYWRIGHT guidance"

require_pattern "codex/designer.prompt.md" "Act as Designer" "Designer prompt role"
require_pattern "codex/designer.prompt.md" "Asset Package" "Designer prompt AP"
require_pattern "codex/designer.prompt.md" "DESIGN_AMBIGUITY" "Designer prompt blocker"
require_pattern "codex/examples/designer.prompt.md" "Act as Designer" "Designer example role"
require_pattern "codex/examples/designer.prompt.md" "Asset Package" "Designer example AP"

require_pattern "codex/pm.prompt.md" "Act as Project Manager" "PM prompt role"
require_pattern "codex/pm.prompt.md" "Decision Request" "PM decision request"
require_pattern "codex/pm.prompt.md" "Orchestrator" "PM Orchestrator boundary"
require_pattern "codex/examples/pm.prompt.md" "Act as Project Manager" "PM example role"
require_pattern "codex/examples/pm.prompt.md" "Communication Package" "PM example CP deployment"

require_pattern "codex/dreamer.prompt.md" "Act as Dreamer" "Dreamer prompt role"
require_pattern "codex/dreamer.prompt.md" "last_collapse.json" "Dreamer last collapse guidance"
require_pattern "codex/dreamer.prompt.md" "docs/dreams/DR" "Dreamer DR path guidance"
require_pattern "codex/dreamer.prompt.md" "Do not create, mutate, or deprecate roles" "Dreamer hard limit guidance"
require_pattern "codex/dreamer.prompt.md" "Do not skip the collapse" "Dreamer collapse guidance"
require_pattern "codex/examples/dreamer.prompt.md" "Act as Dreamer" "Dreamer example role"
require_pattern "codex/examples/dreamer.prompt.md" "docs/dreams/DR" "Dreamer example DR path guidance"
require_pattern "codex/examples/dreamer.prompt.md" "last_collapse.json" "Dreamer example collapse guidance"

require_pattern "codex/evolver.prompt.md" "Act as Evolver" "Evolver prompt role"
require_pattern "codex/evolver.prompt.md" "Dream Reports" "Evolver Dream Reports guidance"
require_pattern "codex/evolver.prompt.md" "PERs" "Evolver PER guidance"
require_pattern "codex/evolver.prompt.md" "CREATE.*MUTATE.*MERGE.*DEPRECATE.*EXTINCT" "Evolver action guidance"
require_pattern "codex/evolver.prompt.md" "docs/evolutions/ER" "Evolver ER path guidance"
require_pattern "codex/evolver.prompt.md" "last_evolution.json" "Evolver last evolution guidance"
require_pattern "codex/examples/evolver.prompt.md" "Act as Evolver" "Evolver example role"
require_pattern "codex/examples/evolver.prompt.md" "CREATE" "Evolver example action guidance"
require_pattern "codex/examples/evolver.prompt.md" "Evolution Report" "Evolver example ER guidance"

require_pattern "codex/inspector.prompt.md" "Playwright" "Inspector Playwright guidance"
require_pattern "codex/inspector.prompt.md" "first-class" "Inspector first-class Playwright"
require_pattern "codex/examples/inspector.prompt.md" "PLAYWRIGHT" "Inspector example PLAYWRIGHT guidance"

require_pattern "codex/sre.prompt.md" "WORLD_MODEL.md" "SRE World Model guidance"
require_pattern "codex/sre.prompt.md" "world_models/" "SRE world models guidance"
require_pattern "codex/sre.prompt.md" "find world_models/" "SRE world models scan"
require_pattern "codex/sre.prompt.md" "no new pattern" "SRE no-new-pattern guidance"
require_pattern "codex/sre.prompt.md" "Pass 0" "SRE Pass 0 guidance"
require_pattern "codex/sre.prompt.md" "classifier.md" "SRE classifier pattern reference"
require_pattern "codex/sre.prompt.md" "Loop permitted" "SRE loop permission guidance"
require_pattern "codex/sre.prompt.md" "UNRECOGNIZED_PATTERN" "SRE unrecognized pattern guidance"
require_pattern "codex/sre.prompt.md" "back-off" "SRE back-off guidance"
require_pattern "codex/sre.prompt.md" "Knowledge Extracted" "SRE Knowledge Extracted guidance"
require_pattern "codex/emergency.prompt.md" "WORLD_MODEL.md" "Emergency World Model guidance"
require_pattern "codex/emergency.prompt.md" "world_models/" "Emergency world models guidance"
require_pattern "codex/emergency.prompt.md" "find world_models/" "Emergency world models scan"
require_pattern "codex/emergency.prompt.md" "classifier.md" "Emergency classifier pattern reference"
require_pattern "codex/emergency.prompt.md" "no new pattern" "Emergency no-new-pattern guidance"
require_pattern "codex/emergency.prompt.md" "below-horizon" "Emergency below-horizon guidance"
require_pattern "codex/emergency.prompt.md" "Knowledge Extracted" "Emergency Knowledge Extracted guidance"
require_pattern "codex/emergency.prompt.md" "commit \\{SHA\\}" "Emergency commit SHA guidance"
require_pattern "codex/examples/sre.prompt.md" "WORLD_MODEL.md" "SRE example World Model guidance"
require_pattern "codex/examples/sre.prompt.md" "world_models/" "SRE example world models guidance"
require_pattern "codex/examples/sre.prompt.md" "find world_models/" "SRE example world models scan"
require_pattern "codex/examples/sre.prompt.md" "Pass 0" "SRE example Pass 0 guidance"
require_pattern "codex/examples/sre.prompt.md" "classifier.md" "SRE example classifier pattern reference"
require_pattern "codex/examples/sre.prompt.md" "back-off" "SRE example back-off guidance"
require_pattern "codex/examples/sre.prompt.md" "Knowledge Extracted" "SRE example Knowledge Extracted guidance"
require_pattern "codex/examples/emergency.prompt.md" "WORLD_MODEL.md" "Emergency example World Model guidance"
require_pattern "codex/examples/emergency.prompt.md" "world_models/" "Emergency example world models guidance"
require_pattern "codex/examples/emergency.prompt.md" "find world_models/" "Emergency example world models scan"
require_pattern "codex/examples/emergency.prompt.md" "classifier.md" "Emergency example classifier pattern reference"
require_pattern "codex/examples/emergency.prompt.md" "Knowledge Extracted" "Emergency example Knowledge Extracted guidance"

require_pattern "codex/world_model_scout.prompt.md" "Act as World Model Scout" "World Model Scout prompt role"
require_pattern "codex/world_model_scout.prompt.md" "FOUND" "World Model Scout FOUND guidance"
require_pattern "codex/world_model_scout.prompt.md" "INFERRED" "World Model Scout INFERRED guidance"
require_pattern "codex/world_model_scout.prompt.md" "UNKNOWN" "World Model Scout UNKNOWN guidance"
require_pattern "codex/world_model_scout.prompt.md" "Do not read bare \\.env" "World Model Scout env safety"
require_pattern "codex/world_model_scout.prompt.md" "Never overwrite" "World Model Scout overwrite safety"
require_pattern "codex/world_model_scout.prompt.md" "Never commit" "World Model Scout commit safety"
require_pattern "codex/examples/world_model_scout.prompt.md" "Act as World Model Scout" "World Model Scout example role"
require_pattern "codex/examples/world_model_scout.prompt.md" "FOUND/INFERRED/UNKNOWN" "World Model Scout example classification"
require_pattern "codex/examples/world_model_scout.prompt.md" "Do not read bare \\.env" "World Model Scout example env safety"

require_pattern "codex/README.md" "harnessable Rubric loop" "README Rubric loop"
require_pattern "codex/README.md" "per-criterion verdict table" "README per-criterion table"
require_pattern "codex/README.md" "WORLD_MODEL.md" "README World Model guidance"
require_pattern "codex/README.md" "world_models/" "README world models guidance"
require_pattern "codex/README.md" "World Model Scout" "README World Model Scout guidance"
require_pattern "codex/README.md" "world_model_scout.prompt.md" "README World Model Scout prompt guidance"
require_pattern "codex/README.md" "FOUND.*INFERRED.*UNKNOWN" "README World Model Scout classification guidance"
require_pattern "codex/README.md" "world_models/.*\\.gitignore" "README world model security guidance"
require_pattern "codex/README.md" "Protocol Enhancement Request" "README PER guidance"
require_pattern "codex/README.md" "Execution Manifest" "README Execution Manifest guidance"
require_pattern "codex/README.md" "packages/\\*/PACKAGE.md" "README package adapter guidance"
require_pattern "codex/README.md" "package commands" "README package command guidance"
require_pattern "codex/README.md" "packages/hallmark" "README Hallmark adapter guidance"
require_pattern "codex/README.md" "agents/skills/hallmark" "README Hallmark install path guidance"
require_pattern "codex/README.md" "Token Budget" "README Token Budget guidance"
require_pattern "codex/README.md" "cost_per_1k_tokens" "README token cost guidance"
require_pattern "codex/README.md" "session_cost_report.py" "README session cost report guidance"
require_pattern "codex/README.md" "classifier.md" "README classifier pattern guidance"
require_pattern "codex/README.md" "error-modes.md" "README error modes guidance"
require_pattern "codex/README.md" "stop authority" "README stop authority guidance"
require_pattern "codex/README.md" "Designer" "README Designer guidance"
require_pattern "codex/README.md" "Project Manager" "README PM guidance"
require_pattern "codex/README.md" "Dreamer" "README Dreamer guidance"
require_pattern "codex/README.md" "Dream Report" "README Dream Report guidance"
require_pattern "codex/README.md" "last_collapse.json" "README last collapse guidance"
require_pattern "codex/README.md" "Evolver" "README Evolver guidance"
require_pattern "codex/README.md" "Evolution Report" "README Evolution Report guidance"
require_pattern "codex/README.md" "Asset Package" "README Asset Package guidance"
require_pattern "codex/README.md" "OPERATOR" "README OPERATOR guidance"
require_pattern "codex/README.md" "PLAYWRIGHT" "README PLAYWRIGHT guidance"

require_pattern "framework/vendor/harnessable/KNOWLEDGE_GRAPH.yaml" "harnessable.PackageAdapter" "PackageAdapter graph concept"
require_pattern "framework/vendor/harnessable/KNOWLEDGE_GRAPH.yaml" "harnessable.PackageSkill" "PackageSkill graph concept"
require_pattern "framework/vendor/harnessable/KNOWLEDGE_GRAPH.yaml" "harnessable.WorldModelScout" "WorldModelScout graph concept"
require_pattern "docs/harness/vendor/harnessable/KNOWLEDGE_GRAPH.yaml" "harnessable.WorldModelScout" "vendored WorldModelScout graph concept"
require_pattern "framework/templates/skills/world_model_scout.md" "FOUND" "World Model Scout skill FOUND guidance"
require_pattern "framework/templates/skills/world_model_scout.md" "INFERRED" "World Model Scout skill INFERRED guidance"
require_pattern "framework/templates/skills/world_model_scout.md" "UNKNOWN" "World Model Scout skill UNKNOWN guidance"
require_pattern "framework/templates/skills/world_model_scout.md" "Do NOT commit" "World Model Scout skill no-commit guidance"

echo "codex_rubric_compatibility: OK"
